### ISSUE TITLE
Inconsistent QQP data with the parsed graph. 

### ISSUE THREAD

**Issue by ccclyu** [ZhaofengWu/SIFT#2]
Thanks again for your nice work! 

I am meeting with the following issue when running the QQP dataset. After I carefully check the current glue dataset (`train.csv` in **QQP**) from its officail website,  your used version (the URL mentioned in the `README`  file is  no longer available ) is a bit different (totally train size is 363,849  while the current glue version is 363,846).  

https://github.com/ZhaofengWu/SIFT/blob/58a0043f459a8507f65ba33cc6ef6bf5c7e00326/data_readers/base_reader.py#L268

To make use of your already parsed graph,  would you mind uploading the QQP zipped dataset that you used for sharing like Google Drive? Or if the public sharing may cause other inconvenience,   could you send the link or the files to my email (changlong.ycl # gmail.com)?  Thanks very much!

**Comment by ZhaofengWu** [comment]
IIRC, there are some pairs with completely empty questions, which should be the source of the discrepancy. If you downloaded the same dataset files as we did and used the same `transformers` version as specified in `requirements.txt`, you should get the same number of training examples. Which URL in the `README` is not working for you?

**Comment by ccclyu** [comment]
The URLs in the downloading glue dataset scripts "https://gist.githubusercontent.com/W4ngatang/60c2bdb54d156a41194446737ce03e2e/raw/17b8dd0d724281ed7c3b2aeeda662b92809aadd5/download_glue_data.py " are not available now.

The new hosted location for QQP from your mentioned [gist](https://gist.github.com/W4ngatang/60c2bdb54d156a41194446737ce03e2e) is https://dl.fbaipublicfiles.com/glue/data/QQP-clean.zip and it is slightly different with the one you used, which casued the inconsistent issue.

**Comment by ZhaofengWu** [comment]
Thanks for noticing this! I've added some instruction at the end of [this section](https://github.com/ZhaofengWu/SIFT#glue-data-and-semantic-graphs). Does that help?

**Comment by ccclyu** [comment]
Thanks for updating the datasets. The issue seems resloved. However the loading features took huge CPU memory as well as time (300GB for more than 2 hours not including training QQP time).  Do you have any tip or experience to reduce the data loading time？ 

By the way, what the computation resources did you use for training (how many gpus / cpu memory, how much time for training),  which are not reported in the paper?

**Comment by ZhaofengWu** [comment]
Yes, we are aware of this -- fortunately, it's only a one-time cost and subsequent training runs should be much less resource-intensive.

We trained on a high-performance computing cluster, with one 24GB GPU (our code doesn't support distributed training). For the largest dataset, iirc, the first-time processing requires 200-300GB of CPU memory as you mentioned, and the following runs require ~50GB of CPU memory. It can take upwards of ~3 days, of course depending on hyperparameters, etc.

**Comment by ccclyu** [comment]
Okay, got it! When I run over multiple GPUs, it didn't work since it doesn't support distributed training as you mentioned. Would pull a request for the support in the near future. Thanks!
