### ISSUE TITLE
May there is a wrong in the paper

### ISSUE THREAD

**Issue by Woodrow1026** [ZhaofengWu/SIFT#5]
in the paper, the CoNLL2015 dataset is used
but it seems like there is no Semantic Dependency Parsing (SDP) share task in CoNLL2015,
maybe it's SemEval 2015 task 18？

**Comment by ZhaofengWu** [comment]
I think you're right. Thanks for catching that! I'll update our arxiv version. Though for our main experiments, we used (a parser trained on) the CoNLL 2019 data, which _is_ for semantic parsing.

**Comment by Woodrow1026** [comment]
So there is also a Semantic dependency parsing task in CoNLL2019？





------------------ Original ------------------
From: Zhaofeng Wu ***@***.***&gt;
Date: Thu,Dec 16,2021 11:25 AM
To: ZhaofengWu/SIFT ***@***.***&gt;
Cc: Woodrow1026 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [ZhaofengWu/SIFT] May there is a wrong in the paper (Issue #5)





 
I think you're right. Thanks for catching that! I'll update our arxiv version. Though for our main experiments, we used the CoNLL 2019 data, which is for semantic parsing.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ZhaofengWu** [comment]
Yes, see http://mrp.nlpl.eu/2019/index.php and https://aclanthology.org/K19-2001.pdf. (Though technically it's not called semantic _dependency_ parsing anymore.)

**Comment by Woodrow1026** [comment]
Thank you！
But I still have a question，in the probing model，there is only one arc classifier or arc/relation classsifier？





------------------ Original ------------------
From: Zhaofeng Wu ***@***.***&gt;
Date: Thu,Dec 16,2021 11:32 AM
To: ZhaofengWu/SIFT ***@***.***&gt;
Cc: Woodrow1026 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [ZhaofengWu/SIFT] May there is a wrong in the paper (Issue #5)

**Comment by ZhaofengWu** [comment]
We have both arc and relation classifiers.
