### ISSUE TITLE
Preprocessed Graphs for HANS

### ISSUE THREAD

**Issue by davidrzs** [ZhaofengWu/SIFT#6]
Dear Zhaofeng,

Thanks for providing the code accompanying your paper.

Do you still have the semantic graphs for the HANS dataset? We are kinda of stuck running the whole preprocessing and thought we would reach out. (we only found them for the GLUE dataset)

Best,
David

**Comment by ZhaofengWu** [comment]
Hi David, thanks for reaching out! Unfortunately we don't have the HANS graphs anymore. Though we do provide instructions on how to generate the graphs in https://github.com/ZhaofengWu/SIFT/blob/master/decode_che_et_al.md. One minor problem is that, at least when we worked on this project, the official CoNLL 2019 pipeline was not public. If this is still the case (probably worth double-checking), you could either reach out to the organizers and ask for it (which we did), or use other tools to perform tokenization and dependency parsing.

**Comment by davidrzs** [comment]
Hi Zhaofeng
Thanks for your fast reply. We saw the instructions but thought there was still some code/preprocessed graphs left for HANS as it requires some reengineering. In that case, we will try to reproduce the pipeline.
Best,
David
