### ISSUE TITLE
inverse relations in the baseline implementation 

### ISSUE THREAD

**Issue by ccclyu** [ZhaofengWu/SIFT#7]
Hi Zhaofeng,  may I ask one clarification question about your baseline implementation? Whether did you use inversed edges (as well as relations) in the syntax (dependency) baseline in Table 3 as the SIFT did? Thanks！

**Comment by ZhaofengWu** [comment]
Yes, if I remember correctly. See the `bidirectional` flag in https://github.com/ZhaofengWu/SIFT/blob/5a6d3acadd5e74f34dcf2f90ae2bfee1dbd45eb3/data_readers/rdf2dgl.py#L59
